language: c
sudo: required
dist: xenial
services:
  - docker
install:
script:
  - docker -v
  - docker-compose -v
  - docker-compose build --no-cache
  - docker-compose run test
matrix:
  fast_finish: true
  include:
    - env: RUBY_VERSION=ruby-2.3 OPENSSL_VERSION=openssl-1.0.2
    - env: RUBY_VERSION=ruby-2.4 OPENSSL_VERSION=openssl-1.0.2
    - env: RUBY_VERSION=ruby-2.5 OPENSSL_VERSION=openssl-1.0.1
    - env: RUBY_VERSION=ruby-2.5 OPENSSL_VERSION=openssl-1.0.2
    - env: RUBY_VERSION=ruby-2.5 OPENSSL_VERSION=openssl-1.1.0
    - env: RUBY_VERSION=ruby-2.5 OPENSSL_VERSION=openssl-1.1.1
    - env: RUBY_VERSION=ruby-2.5 OPENSSL_VERSION=libressl-2.5
    - env: RUBY_VERSION=ruby-2.5 OPENSSL_VERSION=libressl-2.6
    - env: RUBY_VERSION=ruby-2.5 OPENSSL_VERSION=libressl-2.7
    - language: ruby
      rvm: ruby-head
      before_install:
        - "rake install_dependencies"
      script:
        - "rake compile -- --enable-debug"
        - "rake test"
  allow_failures:
    - language: ruby
      rvm: ruby-head
    - env: RUBY_VERSION=ruby-2.5 OPENSSL_VERSION=openssl-1.1.1
